name: Web and API Automation workflow

on:
   workflow_dispatch:  # Manual trigger
   pull_request:
    branches: [ "main" ]  # Trigger on pull request events for the main branch


jobs:

  run-api-automation-test:
  
    runs-on: ubuntu-latest

    steps:

    - uses: actions/checkout@v4

    - name: Set up JDK 11
      uses: actions/setup-java@v4.0.0
      with:
        java-version: '11'
        distribution: 'temurin'

    - name: Set up browser Edge
      uses: browser-actions/setup-edge@v1.1.0

    - name: Set up gradlew
      run : chmod +x gradlew

    - name: Execute API test
      run : ./gradlew apiTest

    - name: Archive Test Result
      uses: actions/upload-artifact@v4.0.0
      if: always()
      with:
        name: api-cucumber-reports
        path: reports

    - name: Deploy report to GitHub Pages
      if: always()
      uses: peaceiris/actions-gh-pages@v3.9.3
      with:
        PERSONAL_TOKEN: ${{ secrets.TOKEN_GITHUB_ACTION }}
        PUBLISH_DIR: reports

  
  
  
  run-web-automation-test:
  
    runs-on: ubuntu-latest

    steps:

    - uses: actions/checkout@v4

    - name: Set up JDK 11
      uses: actions/setup-java@v4.0.0
      with:
        java-version: '11'
        distribution: 'temurin'

    - name: Set up browser Edge
      uses: browser-actions/setup-edge@v1.1.0

    - name: Set up gradlew
      run : chmod +x gradlew

    - name: Execute Web test
      run : ./gradlew webTest

    - name: Archive Test Result
      uses: actions/upload-artifact@v4.0.0
      if: always()
      with:
        name: web-cucumber-reports
        path: reports

    - name: Deploy report to GitHub Pages
      if: always()
      uses: peaceiris/actions-gh-pages@v3.9.3
      with:
        PERSONAL_TOKEN: ${{ secrets.TOKEN_GITHUB_ACTION }}
        PUBLISH_DIR: reports      
